# yaml refs

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"

  webhook:
    image: webhook
    build:
      context: .
      dockerfile: ./src/webhook/Dockerfile
    environment:
      LOG_LEVEL: info

